[package]
name = "chat_server"
version = "0.1.0"
author="Carlos Salguero"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.12", features = ["full"] }